<a href="https://colab.research.google.com/github/hevertonvalerio/estudos/blob/main/projeto_aplicado_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
from sentence_transformers import SentenceTransformer
import warnings
warnings.filterwarnings('ignore')

In [ ]:
warnings.simplefilter('ignore')

# NAO EXECUTAR !!!

### ANALISE E FILTRAGEM DOS DADOS

In [ ]:
df_info = pd.read_csv('/content/drive/MyDrive/Mackenzie/Projeto Aplicado 3/Course_info.csv')

In [ ]:
df_info.head()

       id  ...      instructor_url
0  4715.0  ...   /user/angelapoch/
1  1769.0  ...     /user/ericries/
2  5664.0  ...   /user/angelapoch/
3  7723.0  ...   /user/ian-dunbar/
4  8157.0  ...  /user/edwin-ang-2/

[5 rows x 20 columns]

In [ ]:
df_info.shape

(209734, 20)

In [ ]:
df_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209734 entries, 0 to 209733
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  209734 non-null  float64
 1   title               209734 non-null  object
 2   is_paid             209734 non-null  bool
 3   price               209734 non-null  float64
 4   headline            209703 non-null  object
 5   num_subscribers     209734 non-null  float64
 6   avg_rating          209734 non-null  float64
 7   num_reviews         209734 non-null  float64
 8   num_comments        209734 non-null  float64
 9   num_lectures        209734 non-null  float64
 10  content_length_min  209734 non-null  float64
 11  published_time      209734 non-null  object
 12  last_update_date    209597 non-null  object
 13  category            209734 non-null  object
 14  subcategory         209734 non-null  object
 15  topic               208776 non-null  object
 16  language            209734 non-null  object
 17  course_url          209734 non-null  object
 18  instructor_name     209729 non-null  object
 19  instructor_url      209307 non-null  object
dtypes: bool(1), float64(8), object(11)
memory usage: 30.6+ MB

In [ ]:
df_info.columns

Index(['id', 'title', 'is_paid', 'price', 'headline', 'num_subscribers',
       'avg_rating', 'num_reviews', 'num_comments', 'num_lectures',
       'content_length_min', 'published_time', 'last_update_date', 'category',
       'subcategory', 'topic', 'language', 'course_url', 'instructor_name',
       'instructor_url'],
      dtype='object')

In [ ]:
df_info['language'].unique()

array(['English', 'Spanish', 'Turkish', 'Simplified Chinese', 'Arabic',
       'Portuguese', 'Italian', 'Serbian', 'Afrikaans', 'French',
       'Slovak', 'Japanese', 'Hebrew', 'Traditional Chinese', 'Estonian',
       'German', 'Russian', 'Finnish', 'Dutch', 'Hungarian', 'Swedish',
       'Norwegian', 'Thai', 'Bulgarian', 'Polish', 'Urdu', 'Croatian',
       'Marathi', 'Danish', 'Greek', 'Hindi', 'Indonesian', 'Azeri',
       'Vietnamese', 'Bengali', 'Persian', 'Malay', 'Korean', 'Filipino',
       'Romanian', 'Catalan', 'Czech', 'Albanian', 'Telugu', 'Latvian',
       'Ukrainian', 'Tamil', 'Somali', 'Burmese', 'Kazakh', 'Tatar',
       'Kurdish', 'Aymara', 'Malayalam', 'Uzbek', 'Georgian',
       'Lithuanian', 'Gujarati', 'Pashto', 'Haitian', 'Nepali',
       'Armenian', 'Punjabi', 'Swahili', 'Mongolian', 'Slovenian', 'Zulu',
       'Kannada', 'Guaraní', 'Quechua', 'Macedonian', 'Khmer', 'Frisian',
       'Welsh', 'Irish', 'Basque', 'Xhosa', 'Tajik', 'Faroese'],
      dtype=object)

In [ ]:
df = df_info[['id', 'title', 'price', 'avg_rating', 'headline']].copy()

In [ ]:
df = df_info[df_info['language'].isin(['English', 'Spanish', 'Portuguese'])].copy()

In [ ]:
df.head()

       id  ...      instructor_url
0  4715.0  ...   /user/angelapoch/
1  1769.0  ...     /user/ericries/
2  5664.0  ...   /user/angelapoch/
3  7723.0  ...   /user/ian-dunbar/
4  8157.0  ...  /user/edwin-ang-2/

[5 rows x 20 columns]

In [ ]:
df.shape

(159820, 20)

In [ ]:
df = df_info[(df_info['price'] <= 20) & (df_info['avg_rating'] >= 4.5)].copy()

In [ ]:
df.shape

(26379, 20)

In [ ]:
df = df.dropna(subset=['headline']).copy()

In [ ]:
df.shape

(26373, 20)

In [ ]:
df_final = df.copy()

In [ ]:
df_final['headline'] = df_final['headline'].str.lower()

In [ ]:
df_final.to_csv('df_final.csv', index=False)

# TESTE DO MODELO

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Mackenzie/Projeto Aplicado 3/df_final.csv')

In [ ]:
model = SentenceTransformer('all-mpnet-base-v2')

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
headlines = df['headline'].tolist()

In [ ]:
# embeddings = model.encode(headlines, show_progress_bar=True, device='cuda')

Batches:   0%|          | 0/825 [00:00<?, ?it/s]

In [ ]:
embeddings_path = '/content/drive/MyDrive/Mackenzie/Projeto Aplicado 3/udemy_courses_headline_embeddings.npy'

In [ ]:
# np.save(embeddings_path, embeddings)

# Recommendation - Tests

---

In [ ]:
embeddings = np.load(embeddings_path)

In [ ]:
df = df[['id', 'title', 'price', 'avg_rating', 'course_url', 'instructor_name', 'headline']].copy()

In [ ]:
def recommendation(skills, top_k=100, results=10):
    query = ', '.join(skills)
    query_embedding = model.encode([query])

    similarities = cosine_similarity(query_embedding, embeddings)[0]

    top_k_indices = np.argsort(similarities)[-top_k:][::-1]

    candidate_course = df.iloc[top_k_indices].copy()
    candidate_course['similarity'] = similarities[top_k_indices]
    candidate_course = candidate_course.sort_values('similarity', ascending=False)

    return candidate_course.head(results)

In [ ]:
skills = ['sql', 'software engineering', 'machine learning']

In [ ]:
recommendation(skills, 50, 20)

,id,title,price,avg_rating,course_url,instructor_name,headline,similarity
17784,4139386.0,SQL Masterclass for Data Analysis with BigData,19.99,4.526316,/course/sql-masterclass-for-data-analysis/,Data Is Good Academy,master sql queries and become an in-demand sql...,0.741800
10091,3161274.0,SQL and Data Visualization - The Complete Boot...,19.99,4.575000,/course/sql-data-visualization-the-complete-co...,Raffi Sarkissian | SQL | PostgreSQL | Metabase,"become an expert in sql, data analysis, busine...",0.714356
14020,3734946.0,Introduction of SQL for Analysts [ Arabic ],0.00,4.500000,/course/introduction-of-sql-for-analysts-arabic/,Integral Information Services,boost your career by mastering the high-demand...,0.709106
15323,3880742.0,SQL Bootcamp - Hands-On Exercises - SQLite - P...,19.99,4.500000,/course/sql-bootcamp-hands-on-exercises-sqlite...,Paweł Krakowiak,start your journey with sql and databases. sol...,0.703004
25892,4854236.0,Complete SQL Course for Beginners - with Real ...,19.99,4.800000,/course/complete-sql-course-qadata-analyticsbu...,Pankaj Gupta,complete postgresql course to become an expert...,0.690567
8825,2901794.0,"Data Science with Analogies, Algorithms and So...",0.00,4.500000,/course/data-science-with-analogies-algorithms...,Ajay Dhruv,"machine learning, data mining, data science, d...",0.660105
22303,4544758.0,SQL Mastery For Data Science,19.99,4.500000,/course/sql-mastery-for-data-science/,Joseph M.,up your skills with sql tips and tricks for da...,0.653958
15087,3857472.0,Data Science – End 2 End Beginners Course Part 1,19.99,4.666666,/course/datascience-e2e-beginnerscourse-machin...,Nitin Singhal,"machine learning & data analytics- python, pan...",0.653355
8714,2875266.0,SQL for Beginners: write Queries and create Da...,19.99,4.687500,/course/sql-and-relational-database-course/,Nicola Iantomasi,"learn how to analyze data with sql, write quer...",0.647001
19221,4283846.0,Certified SQL Developer - Practice Tests - 2022,19.99,4.550000,/course/questions-job-interview-sql-developer/,Paweł Krakowiak,get ready for your sql certification or junior...,0.642356
25585,4824890.0,2022 Complete SQL Bootcamp from Zero to Hero i...,7.00,5.000000,/course/2022-complete-sql-bootcamp-from-zero-t...,Surendra Varma Pericherla,become an expert in sql by learning through co...,0.640309
4200,1745282.0,SQL Programming Basics,19.99,4.556531,/course/sql-intro/,Global Academy,learn the fundamentals of sql programming,0.625063
1305,670712.0,SQL Server Administration Part1,19.99,4.601382,/course/sql-server-administration-part1/,Raphael Asghar,sql education with a purpose,0.619848
17473,4109544.0,Google Sheets + MS Excel Course: Basic to Adva...,6.00,4.500000,/course/google-sheets-ms-excel-course-basic-to...,Himanshu Dhar,master google sheets & excel - learn complex d...,0.615955
24004,4680164.0,SQL Bootcamp - SQLite - Hands-On Exercises,19.99,4.900000,/course/sql-bootcamp-sqlite-database-exercises/,Paweł Krakowiak,start your adventure with sql and databases. s...,0.612140
24202,4697478.0,Learn Database Management (DBMS) from Scratch,19.99,5.000000,/course/learn-database-management-dbms-from-sc...,RS Academy,dbms for everyone! enroll to get familiar with...,0.610077
14121,3746148.0,SQL Practice Test for Experts,19.99,5.000000,/course/sql-practice-test-for-experts/,Vijay A,"sql, queries, triggers, transactions, concurre...",0.609066
23211,4616154.0,SQL for Beginners and Non Computer Background ...,19.99,5.000000,/course/simple-and-easy-sql-in-hinglish/,Rohit Kumar Birla,learn how to use sql quickly and effectively w...,0.608051
16923,4045846.0,SQL & PostgreSQL for Beginners: Learn the SQL ...,19.99,4.800000,/course/postgresql-for-beginners-learn-the-fun...,Zaki Khurshid,a comprehensive course on sql and postgresql: ...,0.602676
25598,4826008.0,"SQL for Developers, Data Analysts and BI. MySQ...",19.99,4.921053,/course/mysql-for-everyone/,Nick Ovchinnikov,learn sql with mysql workbench from zero. grea...,0.597714